apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk025-my-app
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk025-my-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: c773988290c46e602860d96deed76072
      labels:
        app: sk025-my-app
    spec:
      serviceAccountName: default
      containers:
      - name: my-app
        image: amdp-registry.skala-ai.com/skala25a/sk025-my-second-app:1.0.kaniko-docker-5-7b44de5804b7
        imagePullPolicy: Always
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: USER_NAME
          value: sk025
        - name: NAMESPACE
          value: skala-practice
